# When you're ready to move to spring-cloud-config then this file should be served by that service
# Eureka server has been added and is available as a sibling to the rest module.

server:
  port: 8080

hello.message: Hello

# When Eureka is available set accordingly
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.11.1:8071/eureka/
  instance:
    status-page-url: ${management.contextPath}/info
    health-check-url-path: ${management.contextPath}/health

management.contextPath: /admin

# Custom actuators
exception.interceptor.queue.size: 50
exception.interceptor.endpoint: exceptions
exception.interceptor.stacktrace: false
trace.interceptor.queue.size: 50
trace.interceptor.endpoint: requests

# If you wish to disable hystrix uncomment
#feign.hystrix.enabled: false

# Please remove this setting - added for demo, see AccountClient
account.service.name: ${spring.application.name}

spring.zipkin.baseUrl: 192.168.11.1:9411
# spring.sleuth.keys.http.headers

---
spring:
  profiles: development


---
spring:
   profiles: test


---
spring:
   profiles: production
